"""
Django settings for kenha_core project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = environ.Path(__file__) - 4
env = environ.Env(DJANGO_READ_DOT_ENV_FILE=False)
APPS_DIR = BASE_DIR.path('CSV_reconciliations_core/apps')


read_dot_env_file = env.bool("DJANGO_READ_DOT_ENV_FILE", "False")
if read_dot_env_file:  # noqa
    env_file = str(BASE_DIR.path(".env"))  # noqa
    print(f"Loading: {env_file}")  # noqa
    env.read_env(env_file)  # noqa
    print(env.list("ALLOWED_HOSTS"))
    print("The .env file has been loaded. See base.py for more information")  # noqa

SECRET_KEY = env.str("SECRET_KEY")

DEBUG = env.bool("DEBUG_MODE")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")

# Application definition

DJANGO_APPS = (
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
)
THIRD_PARTY_APPS = ("django_extensions",)
LOCAL_APPS = ()
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",  # noqa
    "django.contrib.sessions.middleware.SessionMiddleware",  # noqa
    "django.middleware.common.CommonMiddleware",  # noqa
    "django.middleware.csrf.CsrfViewMiddleware",  # noqa
    "django.contrib.auth.middleware.AuthenticationMiddleware",  # noqa
    "django.contrib.messages.middleware.MessageMiddleware",  # noqa
    "django.middleware.clickjacking.XFrameOptionsMiddleware",  # noqa
]

ROOT_URLCONF = "CSV_reconciliations_core.config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


WSGI_APPLICATION = "CSV_reconciliations_core.config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# settings.py


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        
        'NAME': str(BASE_DIR.path("db.sqlite3")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",  # noqa
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",  # noqa
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",  # noqa
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Nairobi"  # Set default timezone to Nairobi, Kenya
USE_TZ = True  # Enable timezone support
USE_I18N = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = f'{BASE_DIR}/staticfiles'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
